const data = [{
    id: 1,
    title: "Azul Duel",
    description: "Decorate a palace ceiling after creating your own pattern.",
    image: "/azul_duel.jpg",
    rating: 8.5,
    category: "Abstract",
    myRating: 8,
    nrOfPlayers: 2,
    playTime: 60,
    year: 2021,
    age: 8,
    weight: 2.2,
  },
  {
    id: 2,
    title: "Lost Ruins of Arnak",
    description: "Explore an island, discover artifacts, and defeat guardians.",
    image: "/lost_ruins_of_arnak.jpg",
    rating: 8.0,
    category: "Strategy",
    myRating: 8,
    nrOfPlayers: 1,
    playTime: 120,
    year: 2020,
    age: 12,
    weight: 2.5,
  },
  {
    id: 3,
    title: "Dune Imperium",
    description: "Influence, intrigue, and combat in the universe of Dune.",
    image: "/dune_imperium.jpg",
    rating: 8.0,
    category: "Strategy",
    myRating: 10,
    nrOfPlayers: 1,
    playTime: 120,
    year: 2020,
    age: 12,
    weight: 3.0,
  },
  {
    id: 4,
    title: "Calico",
    description: "Sew a quilt, collect buttons, attract cats!",
    image: "/calico.jpg",
    rating: 7.5,
    category: "Abstract",
  },
  {
    id: 5,
    title: "Pandemic Legacy",
    description:
      "Mutating diseases are spreading around the world - can your team save humanity? ",
    image: "/pandemic_legacy.jpg",
    rating: 9.5,
    category: "Cooperative",
  },
  {
    id: 6,
    title: "The Crew",
    description:
      "Complete missions in space in this cooperative trick-taking game.",
    image: "/the_crew.jpg",
    rating: 8.0,
    category: "Cooperative",
  },
  {
    id: 7,
    title: "Monopoly",
    description:
      "In this competitive real estate market, there's only one possible outcome: Monopoly! ",
    image: "/monopoly.jpg",
    rating: 3.0,
    category: "Family",
  },
  {
    id: 8,
    title: "Codenames",
    description:
      "Give your team clever one-word clues to help them spot their agents in the field.",
    image: "/codenames.jpg",
    rating: 7.5,
    category: "Party",
  },
  {
    id: 9,
    title: "Catan",
    description:
      "Collect and trade resources to build up the island of Catan in this modern classic.",
    image: "/catan.jpg",
    rating: 7.1,
    category: "Strategy",
  },
]
